### ISSUE TITLE
Wikiwork template call in project pages seems to expect name without underscores

### ISSUE THREAD

**Issue by audiodude** [openzim/wp1#310]
Notice that the wikiwork row is included for: https://en.wikipedia.org/wiki/User:WP_1.0_bot/Tables/Project/Aesthetics

But it's missing for: https://en.wikipedia.org/wiki/User:WP_1.0_bot/Tables/Project/Television_stations

And also missing for: https://en.wikipedia.org/wiki/User:WP_1.0_bot/Tables/Project/Computational_Biology

**Comment by DiyaReddy** [comment]
@audiodude Hello,
from the description i understood that there are wikiwork rows missing in these https://en.wikipedia.org/wiki/User:WP_1.0_bot/Tables/Project/Television_stations
 https://en.wikipedia.org/wiki/User:WP_1.0_bot/Tables/Project/Computational_Biology
I am trying to work and add the rows with their appropriate values and will update you on any changes
Thank You!

**Comment by DiyaReddy** [comment]
@audiodude in the first table which  ω=3,812 and  Ω=4.89 ω
omega =a+2g+3b+4c+5s+6t
where a is A-class articles, g is GA-class articles, b is B-class articles, c is C-class articles, s is start-class articles, and t is stub-class articles.
 Ω= ω/{number of articles}
From the formula we dont have A class articles in the table so by calculating and considering the final value 
value of A=3
so by substituting the value of A we get these desired results.
But I am little confused about the second and third table, should we not consider the value of A because we can not ignore it for the total value to be accurate.
Thank You!

**Comment by audiodude** [comment]
@DiyaReddy The generated templates already have a call for Wikiwork, and the calculation is fine as far as we're concerned.

The bug is extremely minor in that we're passing `Names_with_underscores` while the Wikipedia template for wikiwork seems to prefer `Names without underscores`.
