### ISSUE TITLE
Selection TSV download list should probably better be a redirect

### ISSUE THREAD

**Issue by kelson42** [openzim/wp1#432]
I think we should provide a redirect because in the zimfarm we need a permalink pointing to the latest version.

I would not to erase or delete an older version at the same time we create a new version in the S3. That could lead to strange consequences if for example someone is downloading the TSV at the very same time.

There is also an other "detail", MWoffliner creates the ZIM filename based on the selection filename. Currently this is a random TSV filename which will generate a random ZIM filename.

I'm not sure how should the solution look like exactly, but we probably need to have the slug of the selection name as a filename. If we want to add a bit of random to the filename to identify versions is an open question.

**Comment by audiodude** [comment]
So you're saying, we should keep all versions in s3/local database, but provide an API URL that redirects to the latest version?

You're right that the UUID of the tsv is used as the filename because the list name is not unique, neither across all selections or even for the user's selections.

We could create file paths like: `/selections/org.openzim.wp1.simple/<UUID>/list_name.tsv` would that be acceptable?

**Comment by kelson42** [comment]
@audiodude This woukd indeed offer a proper solution to this ticket, assuming the uuid change from one selection to its nect update.

**Comment by kelson42** [comment]
@audiodude This ticket is pretty important to reuse lists in farm.openzim.org. If OK please put it in WPOD #0

**Comment by audiodude** [comment]
Added
