### ISSUE TITLE
Add indication (spinner or similar) that selection is being computed

### ISSUE THREAD

**Issue by kelson42** [openzim/wp1#434]
For the moment, just after creating the selection, nothing is doable and this is unclear why. We should help the user to understand, he has to wait before being able to download the TSV.

**Comment by audiodude** [comment]
I think we need a more general system for tracking the status of list materialization. We should display an entry for a TSV that is currently queued to be materialized, but has not yet started, and a different display for if materialization is in progress. Something like what we have with manual update progress. It could even be extended to allow the Builder module to update the status, so that a proper progress bar could be displayed.

**Comment by kelson42** [comment]
@audiodude Agree, a status string woukd be better, preciser and extendable.

**Comment by audiodude** [comment]
I'm going to deploy this in the next 10 minutes

**Comment by audiodude** [comment]
Deployed

**Comment by kelson42** [comment]
Seems to work fine to me!
