### ISSUE TITLE
Selection ids are incremental

### ISSUE THREAD

**Issue by kelson42** [openzim/wp1#501]
This is not recommended to have incremental primary ids. We should better have UUI... or any (big enough) random id.

**Comment by audiodude** [comment]
I thought that incremental primary ids were discouraged for sites like YouTube and Twitter, where there is public interest in "how many youtube videos there are", "how many tweets there are" and "downloading every video/tweet".

I don't think any of those are concerns for this project.

**Comment by kelson42** [comment]
To me, the problem is mostly:
* a conceptualy one because I guess this is the primary key of a table. We should better not mix a technical id (like an autoincremented it) and a sementical one (the object id)
* a security concern because if the id can be guessed, half of the job to read objects which are not yours is done.

Here the problem I reported is not that bad, it is just that the behaviour is not really by-the-book. But I want to emphasis that if the impact is limited today, this kind of things might be symptomatic of deeper incoherences and ultimatively lead to bigger problems.

I let you judge of what to do with it. It's OK if we close as WONTFIX.

**Comment by audiodude** [comment]
To be clear, I wasn't taking a stand for the current design. I only wished to explain it so that it could be discussed further. I'm more than open to doing things "by the book", but my understanding was that for small applications like ours, primary keys are convenient to use as visible identifiers.

> a conceptualy one because I guess this is the primary key of a table. We should better not mix a technical id (like an autoincremented primary key) and a sementical one (the object id)

There is no object id for a builder, which is what you're really editing. This might be a larger problem with the misleading language that the frontend uses (everything is "a selection" when really there are both builders and selections in the database). The object id for a selection is like a "foreign key" into s3 storage. It happens to be also used as the primary key for selections, which may already be an abuse of "the book".

> a security concern because if the id can be guessed, half of the job to read objects which are not yours is done.

This is definitely an issue with the current design.

My concern with using some kind of UUID for the primary key of a builder is that we lose the convenience of auto increment primary keys in the database, which are easily generated, set, queried and indexed (though I suppose if we set a string UUID as the primary key it would also get automatically indexed?).

Either way I'm open to discussing it.
