### ISSUE TITLE
All lists are available for everybody via redirect

### ISSUE THREAD

**Issue by kelson42** [openzim/wp1#509]
There is no authentication (which is logic), but because the URL schema is predictable then they can all be checkout. See `https:/api.wp1.openzim.org/v1/builders/36/selection/latest.tsv` which does not belong to me.

Example of the #501 described weakness

**Comment by audiodude** [comment]
This is by design, because I assume the selection is being accessed by a third party site (zimfarm) that does not have login credentials.

Do you want to implement OAuth? 🙃

Making the IDs non monotonically increasing would only mask this problem, because you could still access any builder if you know the ID.

**Comment by audiodude** [comment]
That is, the selections would be "unlisted" but not "private" to use YouTube terminology.

**Comment by kelson42** [comment]
It's good to have the link with authentication but this is bad that all URLs can be guessed. Closing this ticket because this is basically a duplicate of #501, but now we have a real case problem because of the original weakness.
