### ISSUE TITLE
SPARQL based collection of articles is not computed properly

### ISSUE THREAD

**Issue by kelson42** [openzim/wp1#555]
I have a SPARQL request which is:
https://query.wikidata.org/index.html#SELECT%20DISTINCT%20%3Ftopic%20%3FtopicLabel%20%3Farticle%20WHERE%20%7B%0A%20%20%3Fcourse%20wdt%3AP921%20%3Ftopic%3B%0A%20%20%20%20wdt%3AP361%20wd%3AQ113556931.%0A%20%20%3Fc%20wdt%3AP279%20%3Fcurriculum.%0A%20%20%3Fcurriculum%20wdt%3AP31%20wd%3AQ600134.%0A%20%20%3Farticle%20schema%3Aabout%20%3Ftopic%3B%0A%20%20%20%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fen.wikipedia.org%2F%3E.%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%7D

![image](https://user-images.githubusercontent.com/1029718/209464071-70e37f24-f500-4b3b-84e2-dd4ce19f6d90.png)

It is saved properly and it looks like the collection of article is generated properly because no error:
![image](https://user-images.githubusercontent.com/1029718/209464090-431627d7-3e85-4a8c-be5a-ede4bce002bd.png)

But when I click on the "Download tsv", I get:
![image](https://user-images.githubusercontent.com/1029718/209464115-5b8c7349-4811-4adb-8f27-5edd4ac563b0.png)

I would expect that I get the TSV with the same list of article like on Wikidata OR a proper error that something went wrong.

**Comment by audiodude** [comment]
(originally accidentally commented on #556)

The problem here is that the query variable is wrong. The query contains an `?article` subject, but it's really a `url`, the URL on English Wikipedia. The SPARQL Builder API expects the query variable to refer to the subject being selected, in this case the `?topic` query variable. So it should work if you use the same query but use `?topic` as the query variable, in the bottom text box. Tried that and it works.

I don't think we can auto-detect when the user has incorrectly identified the wrong thing in their query as `?article`, or when the query variable doesn't refer to the proper subject, but we can certainly do a better job when the query returns zero results which is ultimately the case in this situation. Perhaps we can offer guidance in an error message about checking that the selected query variable refers to a Wikidata subject (something with a QID).

**Comment by kelson42** [comment]
@audiodude How WP1 knows that the values corresponding to a variable are wrong (here URLs)? Why is this tested at all? 

Another question and sorry if this is a silly one, but are we sure that ?topic IS a WPEN article_id?

**Comment by audiodude** [comment]
WP1 doesn't know anything about the semantics of the query. That's why we suggest that the user tell it the query variable that is selecting the entities of the query.

Here, `?topic` selects entities and `?article` selects Wikipedia URLs. I know that from looking at the query and running it through the WDQS.
