### ISSUE TITLE
Impossible to recreate updated ZIM file

### ISSUE THREAD

**Issue by kelson42** [openzim/wp1#637]
Here is my selections:
![image](https://github.com/openzim/wp1/assets/1029718/fda3cdf7-c56a-47b5-99ef-3e68bf082681)

I click on "Create ZIM" for the "Apple" selection:
![image](https://github.com/openzim/wp1/assets/1029718/75bef047-8556-42cb-8688-1fe6f7f243ca)

At this stage I'm not really sure what is going on. I have clicked on a button called "Create ZIM", then here it's writen "once you request a ZIM file" and there is a button "Download ZIM" ... Whatever, I click on "Download ZIM"

![image](https://github.com/openzim/wp1/assets/1029718/b6b94e27-4ea7-4aa6-9d28-22047ea74263)

I would expect to get either the ZIM file or a clear indication that the creation of a new ZIM has been launched. The message should be also fixed so we use always the same verbs and this is clear what is left to do and/or ongoing.

**Comment by audiodude** [comment]
Good catch! This is because the "ZIM file is deleted" logic is only presentation logic, used to prevent the user from downloading the deleted ZIM on the "Selections" page. However, when you go to the "Create ZIM" page, it finds the old ZIM file and offers to let you download that, but since it's been deleted from the Zimfarm S3, it is a 404.

We need to make sure the Create ZIM file is aware that the old ZIM link is dead and allows you to create a new one. Remember, we don't automatically create new ZIMs for ones that have expired (older than 2 weeks), we wait for the user to request one (as outlined in #581).
