### ISSUE TITLE
Unable to select wikiproject

### ISSUE THREAD

**Issue by Popolechien** [openzim/wp1#774]
Title says it all : when going to https://wp1.openzim.org/#/selections/wikiproject and adding a Wikiproject (plants, in that case, but I tried with others to no avail) I get the following error message `Not all given projects exist` (and then nothing).

Just to be clear I tried to input `plants`, `wikipedia:wikiproject plants` and `wikiproject plants` but no difference.

**Comment by kelson42** [comment]
I confirm there is a bug here, see:
![Image](https://github.com/user-attachments/assets/9c5a3522-3696-4135-adef-4eee370ca316)

@audiodude I suspect something has been broken something

**Comment by audiodude** [comment]
There is no WikiProject called `plants`. There is `Plant` however (https://en.wikipedia.org/wiki/Category:Plant_articles_by_quality). This is apparently case-sensitive.

The strange part is that it's supposed to tell you which project is invalid, like this:

![Image](https://github.com/user-attachments/assets/5d82200f-1a9a-4eb7-9cbf-950bbe027962)

I'm tempted to say "oh the database was unavailable", but that doesn't make sense when looking at the code, since it queries the database to determine whether the project exists and if that had resulted in an error, you would have gotten a 500 error instead.

Also note this line of code: https://github.com/openzim/wp1/blob/main/wp1/selection/models/wikiproject.py#L60

So it wouldn't show the message "Not all given projects exist" unless there was *something* in the `invalid` list. But for some reason that list is empty on the frontend.

Very strange failure mode, though since it's working now I'm going to close as "not reproducible".
